In [ ]:
"""
numpy, pandas 병행
numpy - 데이터전처리 도구
pandas - 분석 도구
"""

In [4]:
# 1차원 배열
import numpy as np
ar=np.array([0,1,2,3,4]) # 배열을 만들때 사용하는 함수
print(ar)

[0 1 2 3 4]


In [10]:
data=list(range(0,100))
ans=[]
# data에 저장된 모든 값들에 대해 2배
for a in data:
    ans.append(2*a)
print(ans)

# 시간 복잡도(cpu) - (연산 결과가 나오기까지 수행되는 라인의 수)
# 공간 복잡도(mem)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]


In [2]:
ans=[]
data=list(range(1,11))
for d in data:
    ans.append(d*2)
print(ans)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [11]:
x=np.array(data)
x*2 # 벡터화 연산 : for 문 사용 x, 한번의연산으로 출력 가능

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [78]:
a=np.array([1,2,3])
# 요소간 연산 : element wise ~~
b=np.array([4,5,6])
a2=[1,2,3]
b2=[4,5,6]

1 2


In [14]:
2*a+b # 벡터화 연산

array([ 6,  9, 12])

In [19]:
#a
a2==2
a==2
a>2

array([False, False,  True])

In [23]:
# 2차원 배열(행렬, matrix)
# 2차원배열 : 리스트의 리스트
# [[0,1,2],[3,4,5]]   -> 열 : 안쪽 리스트 길이, 행 : 바깥쪽 리스트의 길이
m=np.array([[0,1,2],[3,4,5]])
m
len(m) # 행의 갯수
len(m[0]) # 열의 갯수

3

In [26]:
# 3차원 배열 : 리스트의 리스트의 리스트 
m=np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]], # 1행
        [[31,2,3,4],
         [35,6,7,8],
         [39,10,11,12]]]) # 2행
# 2행, 3열, 4깊이(면)
# 2*3*4
len(m) # 2행
len(m[0]) # 3열
len(m[0][0]) # 4 깊이

4

In [31]:
a=np.array([4,5,6])
a.ndim # 배열의 차원
a.shape

(3,)

In [35]:
m=np.array([[0,1,2],[3,4,5]])
m.ndim
m.shape # 2행 3열

(2, 3)

In [38]:
m=np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],
        [[31,2,3,4],
         [35,6,7,8],
         [39,10,11,12]]])
print(m.ndim)
print(m.shape)

3
(2, 3, 4)


In [85]:
# 1번 연속으로 숫자 3개를 곱했을때 얻어진 결과값이 가장 큰 구간이 어디인지 출력
m=np.array([3,2,1,-4,-7,-9,8,-5,3,-1])
n=np.array([0,0,0])
big=0
compare=0
cnt=0
max_cnt=len(m)

for i in m:
    compare = m[cnt]*m[cnt+1]*m[cnt+2]
    if compare > big:
        big = compare
        n*0
        n=m[cnt:cnt+3]
    cnt+=1
    if cnt==8:
        break
print(n)


[-7 -9  8]


In [129]:
# 2번 2*2의 여역을 구성하는 수를 모두 곱했을때 얻어지는 가장 큰 구간이 어디인지 출력
m=np.array([[3,1,-2],
            [2,-1,-3],
            [-2,0,-7]])
# 1,1 / 1,2 / 2,1 / 2,2
n=np.array([[0,0],[0.0]])
big,compare=0,0
cnt=0
# compare = (m[row][col]*m[row+1][col])+(m[row+1][col]*m[row+1][col+1])
for row in range(2):
    for col in range(2):
        compare = (m[row][col]*m[row][col+1])+(m[row+1][col]*m[row+1][col+1])
        if compare > big:
            big = compare
            n*0
            n = [[row,col],[row,col+1],[row+1,col],[row+1,col+1]]
print(n)
    
    


[[1, 1], [1, 2], [2, 1], [2, 2]]


In [104]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
ar
ar[0]
ar[0,:] # 첫번째 행 전체
ar[ : , 1]
ar[1,1:] # 두번째 행에서 두번째 열부터 마지막까지 출력
ar[:2,:2]

array([[1, 2],
       [5, 6]])

In [128]:
# indexing : 데이터 1개를 참조
ar=np.array([0,1,2])
ar[1]
ar[-1]

ar=np.array([[1,2,3,4],[5,6,7,8]])
ar[0,0]
# 다차원 배열에서는 컴마로 접근
ar[0,1] # 2
ar[1,1]
ar[-1,1]
ar[-1,-3]
ar[-1][-3]

6

In [143]:
# 불린 참조 : 조건에 대해 만족하는 값을 추출
ar=np.array([2,3,4,5])
bidx=np.array([True,True,False,True])
ar[bidx]
ar !=4
print(ar[ar !=4])
print(ar[ar %2 == 0  ] )

# ar 요소갑싱 3보다 큰 값들만 추출
print(ar[ar >3])

[2 3 5]
[2 4]
[4 5]


In [166]:
# 정수 참조 추출
ar=np.array([2,3,4,5])
idx=np.array([0,3])
ar[idx] # idx에 요소를 index 번호로 인식해서 참조해서 불러옴
idx=np.array([0,0,1,1])
ar[idx]

[2 5]


array([2, 2, 3, 3])

In [178]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
#[[1,4],
# [5,8]]
idx=np.array([0,3])
print(ar[:,[0,3]])
print(ar[:,[True,False,True,False]])
print(ar[:,[idx]])

[[1 4]
 [5 8]]
[[1 3]
 [5 7]]
[[[1 4]]

 [[5 8]]]


In [198]:
ar=np.array([[1,2,3,4],
             [15,6,7,8],
             [21,2,3,4],
             [35,6,7,8]])
ar[:] # ar 전체 행
ar # 배열 전체
ar[:,:] # 전체 행, 전체 열
# ar[,:] 행에 대해서 써줘야 출력이 됨
print(ar[[2,0],:])
print(ar[[2,0,-1],:])

[[21  2  3  4]
 [ 1  2  3  4]]
[[21  2  3  4]
 [ 1  2  3  4]
 [35  6  7  8]]


In [199]:
# 원데이터: csv, tsv, txt, xls, xlsx, json, ... 
# Pandas: 원데이터를 데이터프레임(엑셀 시트)으로 읽어서 처리
# Numpy: 원데이터를 다차원배열로 읽어서 처리

In [205]:
import pandas as pd
csvTest=pd.read_csv('test_csv.csv')
csvTest

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [206]:
type(csvTest)

pandas.core.frame.DataFrame

In [207]:
csvTest.shape # 5행 3열, (5,3): 튜플

(5, 3)

In [226]:
csvTest.shape[1] # 행, 열 순서


3

In [224]:
# test_text.txt
# 구분자: |
text=pd.read_csv('test_text.txt')
print(text)
print(text.shape)

  ID|LAST_NAME|AGE
0         1|KIM|25
1         2|LEE|22
2        3|PARK|33
3        4|CHOI|24
4         5|CHO|30
(5, 1)


In [223]:
text=pd.read_csv('test_text.txt', sep='|')
print(text)
print(text.shape)

   ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30
(5, 3)


In [295]:
# 수업연습문제 - 1번 연속으로 숫자 3개를 곱했을때 얻어진 결과값이 가장 큰 구간이 어디인지 출력
m=np.array([3,2,1,-4,-7,-9,8,-5,3,-1])
n=np.array([0,0,0])
big=0
compare=0
cnt=0
max_cnt=len(m)

for i in m:
    compare = m[cnt]*m[cnt+1]*m[cnt+2]
    if compare > big:
        big = compare
        n=m[cnt:cnt+3]
    cnt+=1
    if cnt==8:
        break
print(n)


[-7 -9  8]


In [308]:
# 수업연습문제 - 2번 2*2의 여역을 구성하는 수를 모두 곱했을때 얻어지는 가장 큰 구간이 어디인지 출력
m=np.array([[3,1,-2],
            [2,-1,-3],
            [-2,0,-7]])
# 1,1 / 1,2 / 2,1 / 2,2
big = -500
compare = -500
cnt=0
# compare = (m[row][col]*m[row+1][col])+(m[row+1][col]*m[row+1][col+1])
for row in range(len(b)-1):
    for col in range(len(b)-1):
        compare = m[row][col]*m[row][col+1]*m[row+1][col]*m[row+1][col+1]
        if compare > big:
            big = compare
            n = [m[row,col],m[row,col+1]],[m[row+1,col],m[row+1,col+1]]
        else:
            continue

print(n)
    


([2, -1], [-2, 0])


In [239]:
# 1번
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
print(m[1,2])
print(m[2,4])
print(m[1,1:3])
print(m[1:,2])
print(m[0:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [274]:
# 2번
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0)&(x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [369]:
# 3번
height=[7,4,2,7,0,6,]
zero=np.zeros((10,10))
cnt=0
max_val=0
near=0
cnt_near=0
compare_near=0
for i in height:
    if i !=0:
        zero[cnt,:i]=1
    cnt+=1

print(zero)    
for i in range(10):
    for j in range(10):
        if zero[i,j] == 1:
            for k in range(10):
                if zero[k][j]==0:
                    cnt_near+=1
                elif zero[k][j]==1:
                    compare_near=cnt_near
                    cnt_near=0
            if near < compare_near:
                near = compare_near
                
    
print(near)

[[1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2
