In [34]:
# 신경망 구현(라이브러리 x)
import numpy as np
import math
X=np.array([1,2,3,4])
np.ndim(X) # 1차원 배열
# 차원의 수
X.shape[0] # (4,) : 1차원

4

In [15]:
X=np.array([[1,2],[3,4],[5,6]]) # 2차원 배열
np.ndim(X)
X.shape
# 0번째 차원, 1번째 차원

(3, 2)

In [18]:
X=np.array([[1,2],[3,4]])
Y=np.array([[5,6],[7,8]])
# 행렬의 곱(내적)
np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [28]:
X=np.array([1,2])
W=np.array([[1,3,5],[2,4,6]])
Y=np.dot(X,W)
Y

array([ 5, 11, 17])

In [39]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [50]:
# 2, 3, 2, 2 fully connected
X=np.array([1.0,0.5])
W1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])  # (2,3)
B1=np.array([0.1,0.2,0.3])
H1=np.dot(X,W1)+B1
Z1=sigmoid(H1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [51]:
W2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2=np.array([0.1,0.2])
H2=np.dot(Z1,W2)+B2
Z2=sigmoid(H2)
Z2

array([0.62624937, 0.7710107 ])

In [52]:
W3=np.array([[0.1,0.2],[0.2,0.3]])
B3=np.array([0.1,0.2])
H3=np.dot(Z2,W3)+B3
H3

array([0.31682708, 0.55655308])

In [54]:
scores=np.array([20,10,1])
exp_s=np.exp(scores) # 지수함수

In [56]:
sum_exp_s=np.sum(exp_s)
sum_exp_s

485187224.5938669

In [57]:
y=exp_s/sum_exp_s
y

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])

In [69]:
def relu(x):
    a=[]
    for i in x:
        if i>0:
            a.append(i)
        else:
            a.append(0)
            
    return a

In [75]:
x=np.array([2,3])
w1=np.array([[1,2,3],[4,5,6]])
H1=np.dot(x,w1)
Z1=relu(H1)
w2=np.array([[1,2],[3,4],[5,6]])
H2=np.dot(Z1,w2)
w3=np.array([[1],[2]])
Z=np.dot(H2,w3)
Z

array([687])

In [67]:
a=[]
for i in H1:
    if i>0:
        a.append(i)
    else:
        a.append(0)

In [68]:
a

[14, 19, 24]