In [27]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

In [29]:
iris=datasets.load_iris()
iris

data=pd.DataFrame(iris.data, columns=iris.feature_names)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [32]:
data_std=StandardScaler().fit_transform(data)
data_std
data_std_df=pd.DataFrame(data_std, columns=iris.feature_names)
data_std_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [40]:
f=data_std.T
cov_matrix=np.cov(f)
cov_matrix
eig_vals, eig_vecs=np.linalg.eig(cov_matrix)
print("고유벡터 \n %s"%eig_vecs)
print("고유값 \n %s"%eig_vals)

고유벡터 
 [[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]
고유값 
 [2.93808505 0.9201649  0.14774182 0.02085386]


In [41]:
for i in eig_vals:
    print(i/sum(eig_vals))

# 0.7296244541329985
# 0.2285076178670178
# 0.03668921889282875
# 0.005178709107154802

0.7296244541329985
0.2285076178670178
0.03668921889282875
0.005178709107154802


In [53]:
sepal=eig_vecs[:2]
petal=eig_vecs[2:]
sepal.shape # 2 x 4

(2, 4)

In [58]:
sepal_data=np.dot(data_std,sepal.T)
sepal_data 
sepal_data.shape # 150 x 2

(150, 2)

In [56]:
petal_data=np.dot(data_std,petal.T)
petal_data
petal_data.shape # 150 x 2

(150, 2)

In [59]:
data_std.shape # 150 x 4

(150, 4)