In [1]:
import nltk
nltk.__version__

'3.4.5'

In [3]:
nltk.download() # nltk data 다운로드
# github.com/nltk

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [2]:
import konlpy
konlpy.__version__

'0.5.2'

In [ ]:
# JPype : 자바와 파이썬 연결


In [3]:
# 토큰화, 정제, 정규화
# 토큰화 :어절, 단어, 문장, 문단
# 단어 토큰화
from nltk.tokenize import word_tokenize

In [4]:
print(word_tokenize("Mr. Jone's Don't be!"))

['Mr.', 'Jone', "'s", 'Do', "n't", 'be', '!']


In [5]:
from nltk.tokenize import WordPunctTokenizer

print(WordPunctTokenizer().tokenize("Mr. Jone's Don't be"))

['Mr', '.', 'Jone', "'", 's', 'Don', "'", 't', 'be']


In [6]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [7]:
text_to_word_sequence("Mr. Jone's Don't be!")

['mr', "jone's", "don't", 'be']

In [8]:
from nltk.tokenize import TreebankWordTokenizer

In [9]:
twt=TreebankWordTokenizer()
print(twt.tokenize("Mr. Jone's Don't be!"))

# TreebankWordTokenizer, word_tokenize 가 표준으로 가장 많이 사용 

['Mr.', 'Jone', "'s", 'Do', "n't", 'be', '!']


In [10]:
from nltk.tokenize import sent_tokenize
text="Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [11]:
print(sent_tokenize(text)) # 토큰의 단위가 문장

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [12]:
# 한국어 분석의 문제점 -> 조사
# 한국어 토큰화 작업 : 형태소(가장 작은 말의 단위) 고려 필수
# 자립 형태소(길동이, 파이썬) / 의존 형태소 (조사, 어미, ...)
# ex) 길동이가 파이썬을 합니다

In [13]:
# 품사 태깅(tagging), fly

In [14]:
text='Python is an interpreted, high-level, general-purpose programming language.'
print(word_tokenize(text))

from nltk.tag import pos_tag
pos_tag(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [15]:
# 형태소 분석기 : Okt, Mecab, Kkma...
# 단어토큰화가 아님, 형태소 단위로 토큰화를 하는 것
from konlpy.tag import Okt

In [16]:
okt=Okt()
# Okt버전이랑 jpype1 버전이 맞이 않은 경우 에러가 발생함
# pip install jpype1==0.7.0 처럼 수정
print(okt.morphs("오늘은 수요일, 내일은 목요일입니다")) # 형태소를 추출하는 함수
print(okt.pos("오늘은 수요일, 내일은 목요일입니다")) # 품사를 추출하는 함수
print(okt.nouns("오늘은 수요일, 내일은 목요일입니다")) # 명사를 추출하는 함수

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective')]
['오늘', '수요일', '내일', '목요일']


In [17]:
from konlpy.tag import Kkma
kma=Kkma()
kma.morphs('꾸어어어어')

['꾸', '어', '어', '어', '얼']

In [18]:
# 데이터 정제(전처리) : 불필요한 형태소 제거, 단어 통일
# 정규표현식을 이용 


In [19]:
import numpy as np
A=np.array([[0,0,0,1,0,1,1,0,0],
            [0,0,0,1,1,0,1,0,0],
            [0,1,1,0,2,0,0,0,0],
            [1,0,0,0,0,0,0,1,1]])
A.shape

U, s, VT=np.linalg.svd(A, full_matrices=True)

In [20]:
U.round(2) # 직교행렬
s.round(2)

array([2.69, 2.05, 1.73, 0.77])

In [21]:
S=np.zeros((4,9))
S[:4,:4]=np.diag(s)
S.round(2) # 특이값 행렬

array([[2.69, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 2.05, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.73, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.77, 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [22]:
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ],
       [ 0.58, -0.  ,  0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.58,  0.58],
       [ 0.  , -0.35, -0.35,  0.16,  0.25, -0.8 ,  0.16, -0.  , -0.  ],
       [-0.  , -0.78, -0.01, -0.2 ,  0.4 ,  0.4 , -0.2 ,  0.  ,  0.  ],
       [-0.29,  0.31, -0.78, -0.24,  0.23,  0.23,  0.01,  0.14,  0.14],
       [-0.29, -0.1 ,  0.26, -0.59, -0.08, -0.08,  0.66,  0.14,  0.14],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19,  0.75, -0.25],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19, -0.25,  0.75]])

In [23]:
np.allclose(A,np.dot(np.dot(U,S),VT).round(2))

True

In [24]:
# 절단된(truncated) SVD
# 토픽 2개
S=S[:2,:2]
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [25]:
U.shape # 4,4
U=U[:,:2] # 4,2
# U의 의미는 4개 문서 각각에 대한 잠재된 의미를 표현하고 있는 수치 문서 벡터
U.round(2)

array([[-0.24,  0.75],
       [-0.51,  0.44],
       [-0.83, -0.49],
       [-0.  , -0.  ]])

In [26]:
VT.shape # 9,9
VT=VT[:2,:] # 2,9 => 토픽 * 단어개수
# VT 각 열은 잠재 의미를 나타내기 위한 수치화된 단어 벡터
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

In [27]:
Aprime=np.dot(np.dot(U,S),VT).round(2)
print(Aprime)
print(A)

[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


In [28]:
np.dot(S,VT).round(2)

array([[-0.  , -0.83, -0.83, -0.75, -2.16, -0.24, -0.75, -0.  , -0.  ],
       [ 0.  , -0.49, -0.49,  1.2 , -0.53,  0.75,  1.2 , -0.  , -0.  ]])

In [ ]:
"""
           돈   사랑   저는    좋아요
줄거리 1   0    1      1       1
줄거리 2   1    0      1       1 
줄거리 3   2    0      2       2
"""

In [29]:
from numpy.linalg import norm

In [30]:
mov1=np.array([0,1,1,1])
mov2=np.array([1,0,1,1])
mov3=np.array([2,0,2,2])

In [31]:
np.dot(mov1,mov2) # 두 벡터의 내적
np.dot(mov1,mov2)/(norm(mov1)*norm(mov2))

def cos_sim(X,Y):
    return np.dot(X,Y)/(norm(X)*norm(Y))

print(cos_sim(mov1,mov2))
print(cos_sim(mov2,mov3))
print(cos_sim(mov1,mov3))

0.6666666666666667
1.0000000000000002
0.6666666666666667


In [55]:
import pandas as pd

data=pd.read_csv("the-movies-dataset/movies_metadata.csv")
data=data.head(20000)

C:\Users\student\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [99]:
data['overview'].isnull()
data['overview'].fillna('',inplace=True)
data['title'][1]

'Jumanji'

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(stop_words='english')
tfidf_mat = tfidf.fit_transform(data['overview']) # tf-idf matrix 생성
tfidf_mat = tfidf_mat.toarray() 


In [101]:
tfidf_mat.shape[0]

20000

In [102]:
ToyStory=tfidf_mat[0]

In [103]:
def cos_sim(X,Y):
    return np.dot(X,Y)/(norm(X)*norm(Y))

def similar_toystory(data, ToyStory, tfidf_mat):
    movie_list=[]
    for i in range(1, tfidf_mat.shape[0]):
        cos=cos_sim(ToyStory,tfidf_mat[i])
        movie_list.append([data['title'][i],cos])
    movie_list=sorted(movie_list, key=lambda s:s[1], reverse=True)
    
    return movie_list[:10]

similar_toystory(data, ToyStory,tfidf_mat)

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in double_scalars
  


[['The 40 Year Old Virgin', 0.2795541150488133],
 ['Malice', 0.1375106791269381],
 ['For Love or Money', 0.11656473849605975],
 ['Window to Paris', 0.06547657266141106],
 ['Mute Witness', 0.06397135942434755],
 ['Safe Passage', 0.04526684118307106],
 ['Carried Away', 0.04369986367616119],
 ['Four Rooms', 0.04113995020790759],
 ['Pretty Woman', 0.040530287641558756],
 ['Much Ado About Nothing', 0.03869944498425505]]

In [199]:
a=similar_toystory(tfidf_mat)
print(a)

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in double_scalars
  


[(nan, 19909), (0.018138871622511377, 19916), (0.019853155734699927, 19969), (0.024584793469282384, 19997), (0.027105644611392515, 19970), (0.0524938793119962, 17646), (0.06099673588133421, 19993), (0.06369332191395058, 18061), (0.07448744944250994, 19876), (0.11798196632714826, 19977)]


In [215]:
data['title'][0]

'Toy Story'