In [76]:
import numpy as np
import sys

In [ ]:
s=input().split(" ")
data=[]
moving_num=int(s[0])
for i in range(len(s)-1):
    data.append(s[i+1])
data=data[-moving_num:]+data[0:-moving_num]
print(data)


##### 

In [ ]:
k=list(input())
for i in k:
    if i==' ':
        input_data.remove(i)

In [ ]:
s=[0,1,0,0,0,0,0,0,0,0,1]
cnt=0
print(len(s))
for i in s:
    if i==1:
        print(cnt)
    cnt+=1
s[10]

In [96]:
s=input().split()
width=int(s[0])
height=int(s[1])
s=(width,height)

data=np.zeros((width,height))

print(data, end="\n")
print("="*50)
        
n=input()
num_list=[]
for i in n:
    if i.isnumeric():
        num_list.append(int(i))
        
x=num_list[0]
y=num_list[1]
color=num_list[2]

k=list(input())

for i in k:
    if i==' ':
        k.remove(i)
print(data)        
cnt=0

for i in range(width):
    for j in range(height):
        data[i][j]=k[cnt]
        cnt+=1
    
data
def paint(x,y):
    global width, height
    
    if x in range(1,width+1) and y in range(1,height+1):
        if data[y][x]==0:
            data[y][x]=color
        
            paint(x+1,y)
            paint(x-1,y)
            paint(x,y+1)
            paint(x,y-1)
            

print(x,y,color)
paint(x,y)
data

10 10
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
6 6 3
0000000000 0000001000 0000110100 0011000010 0100000010 0100000010 0100000100 0010001000 0001011000 0000100000
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
6 6 3


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 3., 1., 0., 0.],
       [0., 0., 1., 1., 3., 3., 3., 3., 1., 0.],
       [0., 1., 3., 3., 3., 3., 3., 3., 1., 0.],
       [0., 1., 3., 3., 3., 3., 3., 3., 1., 0.],
       [0., 1., 3., 3., 3., 3., 3., 1., 0., 0.],
       [0., 0., 1., 3., 3., 3., 1., 0., 0., 0.],
       [0., 0., 0., 1., 3., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [82]:
data[1][1]=3
data

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])